import { createContext, useContext } from "react";

const ru = {
  app: {
    answerColumn: "Твой ответ",
    codeColumn: "Код",
    codeColumnAriaLabel: "Код задачи",
    visualizationColumn: "Визуализация",
    visualizationColumnAriaLabel: "Визуализация Event Loop",
    visualizationAfterCheck: "Нажмите «анимация event loop», чтобы увидеть выполнение.",
    visualizationBeforeCheck: "Проверьте ответ, чтобы запустить анимацию Event Loop.",
  },
  header: {
    colorThemes: {
      midnight: "Ночной",
      ocean: "Океан",
      forest: "Лес",
      rose: "Роза",
    },
    kicker: "event loop · тренажер",
    titleBeforeConsole: "В каком порядке выполнится ",
    colorThemeAriaLabel: "Цветовая схема",
    colorThemeAriaLabelWithName: (name: string) => `Цветовая схема: ${name}`,
    languageAriaLabel: "Язык интерфейса",
    streak: "серия",
    record: "рекорд",
    solved: "решено",
  },
  levelSelector: {
    level: "Сложность",
    theme: "Тема",
    taskThemeAriaLabel: "Тема задания",
    themeTitle: (name: string) => `Тема: ${name}`,
    unavailableThemeTitle: "Эта тема доступна на уровнях Medium и Hard",
    newTask: "↻ новая задача",
  },
  taskActions: {
    check: "Проверить",
    reset: "сбросить",
    retryMistakes: (count: number) => `↻ ошибки (${count})`,
    correct: "✓ Верно!",
    successHint: "Отлично! Ты правильно собрал порядок вывода.",
    incorrect: "✗ В другой раз повезёт",
    next: "Следующая →",
    retryTask: "↻ Повторить эту задачу",
    hideAnimation: "⏹ скрыть анимацию",
    showAnimation: "▶ анимация event loop",
    hideExplanation: "скрыть разбор",
    showExplanation: "разбор",
  },
  taskCodePanel: {
    fileName: "task.js",
    loading: "// собираю задачу…",
    generationFailed: "// не удалось собрать задачу — попробуйте ещё раз",
  },
  taskExplanation: {
    title: "ПОЧЕМУ ТАКОЙ ПОРЯДОК",
    rule: {
      prefix: "Правило: ",
      syncCode: "синхронный код",
      allMicrotasks: "все микрозадачи",
      microtaskExamples: " (Promise.then, queueMicrotask, код после await) ",
      macrotasks: "макрозадачи",
      macrotaskExamples: " (setTimeout) по одной, и после каждой — снова все микрозадачи.",
    },
  },
  answerConsole: {
    title: "Console — твой прогноз",
    remove: "убрать",
    expected: "→ должно быть ",
  },
  tokenPicker: {
    instruction: "НАЖИМАЙ В ТОМ ПОРЯДКЕ, В КОТОРОМ ПОЯВИТСЯ ВЫВОД",
    progress: (selected: number, total: number) => `Выбрано ${selected} из ${total}`,
  },
  eventLoopViz: {
    previousStep: "Предыдущий шаг",
    restart: "Запустить заново",
    pause: "Пауза",
    continue: "Продолжить",
    nextStep: "Следующий шаг",
    reason: "Почему этот шаг?",
    callStack: "Call Stack",
    empty: "пусто",
    flowAriaLabel: "Состояние цикла событий",
    microtaskQueue: "Microtask Queue · FIFO →",
    taskQueue: "Task Queue · FIFO →",
    console: "CONSOLE",
    noOutput: "вывода пока нет",
    pending: "ожидают",
  },
  levels: {
    easy: { label: "Легко", description: "синхронный код, таймеры и простые микрозадачи вперемешку" },
    medium: { label: "Средне", description: "async/await, вложенность, цепочки и ловушки" },
    hard: { label: "Сложно", description: "монструозные задачи со злых собеседований: много логов, всё вперемешку" },
  },
  themes: {
    all: "Все темы",
    microtasks: "Микрозадачи",
    timers: "Таймеры",
    async: "async / await",
  },
  phases: {
    sync: { name: "синхронно", hint: "выполняется сразу, стек вызовов" },
    macro: { name: "макрозадача", hint: "setTimeout попадает в очередь таймеров" },
    macroSlow: { name: "макрозадача (задержка)", hint: "таймер с большей задержкой сработает позже" },
    micro: { name: "микрозадача", hint: "очередь микрозадач опустошается до таймеров" },
    awaitAfter: { name: "микрозадача (после await)", hint: "код после await — это .then()" },
    microInMacro: { name: "микрозадача внутри таймера", hint: "микрозадачи выполняются сразу после колбэка таймера" },
    macroNested: { name: "вложенный setTimeout", hint: "новый таймер встаёт в конец очереди" },
    macroFromMicro: { name: "setTimeout из микрозадачи", hint: "таймер регистрируется позже синхронных" },
    executor: { name: "синхронно (executor)", hint: "функция внутри new Promise выполняется сразу" },
  },
  sim: {
    scriptStart: "Скрипт выполняется сверху вниз",
    executor: (label: string) => `new Promise: executor выполняется синхронно → лог '${label}'`,
    syncLog: (label: string) => `console.log('${label}') — синхронно, прямо в стеке`,
    awaitQueued: (label: string) => `await приостанавливает функцию: продолжение '${label}' → микрозадачи`,
    microQueued: (labels: string) => `Колбэк ${labels} → очередь микрозадач`,
    slowTimerQueued: (label: string) => `setTimeout(…, 100): колбэк '${label}' → очередь задач (сработает позже)`,
    timerQueued: (labels: string) => `setTimeout регистрирует колбэк ${labels} → очередь задач`,
    scriptEnd: "Скрипт закончился — стек вызовов пуст",
    nextAwaitQueued: (label: string) => `Следующий await: продолжение '${label}' → очередь микрозадач`,
    nestedMicroQueued: (parent: string, label: string) => `Изнутри '${parent}': колбэк '${label}' → очередь микрозадач`,
    nestedTimerQueued: (parent: string, label: string) => `Изнутри '${parent}': новый setTimeout '${label}' → очередь задач`,
    microRunning: (labels: string) => `Стек пуст → микрозадача ${labels} выполняется: console.log`,
    macroRunning: (labels: string) => `Микрозадач нет → тик цикла: задача ${labels} из очереди`,
    complete: "Очереди пусты — программа отработала ✓",
  },
} as const;

const en = {
  app: {
    answerColumn: "Your answer",
    codeColumn: "Code",
    codeColumnAriaLabel: "Task code",
    visualizationColumn: "Visualization",
    visualizationColumnAriaLabel: "Event Loop visualization",
    visualizationAfterCheck: "Press “event loop animation” to see the execution.",
    visualizationBeforeCheck: "Check your answer to start the Event Loop animation.",
  },
  header: {
    colorThemes: { midnight: "Midnight", ocean: "Ocean", forest: "Forest", rose: "Rose" },
    kicker: "event loop · trainer",
    titleBeforeConsole: "What is the order of ",
    colorThemeAriaLabel: "Color theme",
    colorThemeAriaLabelWithName: (name: string) => `Color theme: ${name}`,
    languageAriaLabel: "Interface language",
    streak: "streak",
    record: "record",
    solved: "solved",
  },
  levelSelector: {
    level: "Difficulty",
    theme: "Topic",
    taskThemeAriaLabel: "Task topic",
    themeTitle: (name: string) => `Topic: ${name}`,
    unavailableThemeTitle: "This topic is available on Medium and Hard levels",
    newTask: "↻ new task",
  },
  taskActions: {
    check: "Check",
    reset: "reset",
    retryMistakes: (count: number) => `↻ mistakes (${count})`,
    correct: "✓ Correct!",
    successHint: "Great job! You put the output in the right order.",
    incorrect: "✗ Not quite",
    next: "Next →",
    retryTask: "↻ Retry this task",
    hideAnimation: "⏹ hide animation",
    showAnimation: "▶ event loop animation",
    hideExplanation: "hide explanation",
    showExplanation: "explanation",
  },
  taskCodePanel: {
    fileName: "task.js",
    loading: "// building task…",
    generationFailed: "// could not build a task — try again",
  },
  taskExplanation: {
    title: "WHY THIS ORDER",
    rule: {
      prefix: "Rule: ",
      syncCode: "synchronous code",
      allMicrotasks: "all microtasks",
      microtaskExamples: " (Promise.then, queueMicrotask, code after await) ",
      macrotasks: "macrotasks",
      macrotaskExamples: " (setTimeout) one at a time, followed by all microtasks again.",
    },
  },
  answerConsole: { title: "Console — your prediction", remove: "remove", expected: "→ expected " },
  tokenPicker: {
    instruction: "CLICK IN THE ORDER THE OUTPUT WILL APPEAR",
    progress: (selected: number, total: number) => `${selected} of ${total} selected`,
  },
  eventLoopViz: {
    previousStep: "Previous step",
    restart: "Restart",
    pause: "Pause",
    continue: "Continue",
    nextStep: "Next step",
    reason: "Why this step?",
    callStack: "Call Stack",
    empty: "empty",
    flowAriaLabel: "Event loop state",
    microtaskQueue: "Microtask Queue · FIFO →",
    taskQueue: "Task Queue · FIFO →",
    console: "CONSOLE",
    noOutput: "no output yet",
    pending: "pending",
  },
  levels: {
    easy: { label: "Easy", description: "synchronous code, timers, and simple microtasks mixed together" },
    medium: { label: "Medium", description: "async/await, nesting, chains, and traps" },
    hard: { label: "Hard", description: "monster interview tasks: lots of logs, all mixed together" },
  },
  themes: { all: "All topics", microtasks: "Microtasks", timers: "Timers", async: "async / await" },
  phases: {
    sync: { name: "synchronous", hint: "runs immediately on the call stack" },
    macro: { name: "macrotask", hint: "setTimeout enters the timer queue" },
    macroSlow: { name: "macrotask (delayed)", hint: "a longer timer fires later" },
    micro: { name: "microtask", hint: "the microtask queue drains before timers" },
    awaitAfter: { name: "microtask (after await)", hint: "code after await is a .then()" },
    microInMacro: { name: "microtask inside a timer", hint: "microtasks run right after the timer callback" },
    macroNested: { name: "nested setTimeout", hint: "the new timer goes to the end of the queue" },
    macroFromMicro: { name: "setTimeout from a microtask", hint: "the timer is registered after synchronous code" },
    executor: { name: "synchronous (executor)", hint: "the function inside new Promise runs immediately" },
  },
  sim: {
    scriptStart: "The script runs from top to bottom",
    executor: (label: string) => `new Promise: the executor runs synchronously → log '${label}'`,
    syncLog: (label: string) => `console.log('${label}') — synchronous, directly on the stack`,
    awaitQueued: (label: string) => `await pauses the function: continuation '${label}' → microtask queue`,
    microQueued: (labels: string) => `Callback ${labels} → microtask queue`,
    slowTimerQueued: (label: string) => `setTimeout(…, 100): callback '${label}' → task queue (fires later)`,
    timerQueued: (labels: string) => `setTimeout registers callback ${labels} → task queue`,
    scriptEnd: "The script ended — the call stack is empty",
    nextAwaitQueued: (label: string) => `Next await: continuation '${label}' → microtask queue`,
    nestedMicroQueued: (parent: string, label: string) => `Inside '${parent}': callback '${label}' → microtask queue`,
    nestedTimerQueued: (parent: string, label: string) => `Inside '${parent}': new setTimeout '${label}' → task queue`,
    microRunning: (labels: string) => `Stack is empty → microtask ${labels} runs: console.log`,
    macroRunning: (labels: string) => `No microtasks → event-loop tick: task ${labels} from the queue`,
    complete: "Queues are empty — the program has finished ✓",
  },
} as const;

export const localizedStrings = { ru, en };
export type Strings = typeof ru | typeof en;

const StringsContext = createContext<Strings>(ru);

export const StringsProvider = StringsContext.Provider;
export const useStrings = () => useContext(StringsContext);
