export const strings = {
  app: {
    answerColumn: "Твой ответ",
    codeColumn: "Код",
    codeColumnAriaLabel: "Код задачи",
    visualizationColumn: "Визуализация",
    visualizationColumnAriaLabel: "Визуализация Event Loop",
    visualizationAfterCheck: "Нажмите «анимация event loop», чтобы увидеть выполнение.",
    visualizationBeforeCheck: "Проверьте ответ, чтобы запустить анимацию Event Loop.",
  },
  header: {
    colorThemes: {
      midnight: "Ночной",
      ocean: "Океан",
      forest: "Лес",
      rose: "Роза",
    },
    kicker: "event loop · тренажер",
    titleBeforeConsole: "В каком порядке ",
    colorThemeAriaLabel: "Цветовая схема",
    colorThemeAriaLabelWithName: (name: string) => `Цветовая схема: ${name}`,
    streak: "серия",
    record: "рекорд",
    solved: "решено",
  },
  levelSelector: {
    level: "Сложность",
    theme: "Тема",
    taskThemeAriaLabel: "Тема задания",
    themeTitle: (name: string) => `Тема: ${name}`,
    unavailableThemeTitle: "Эта тема доступна на уровнях Medium и Hard",
    newTask: "↻ новая задача",
  },
  taskActions: {
    check: "Проверить",
    reset: "сбросить",
    retryMistakes: (count: number) => `↻ ошибки (${count})`,
    correct: "✓ Верно!",
    incorrect: "✗ Не совсем",
    next: "Следующая →",
    retryTask: "↻ Повторить эту задачу",
    hideAnimation: "⏹ скрыть анимацию",
    showAnimation: "▶ анимация event loop",
    hideExplanation: "скрыть разбор",
    showExplanation: "разбор",
  },
  taskCodePanel: {
    fileName: "task.js",
    loading: "// собираю задачу…",
  },
  taskExplanation: {
    title: "ПОЧЕМУ ТАКОЙ ПОРЯДОК",
    rule: {
      prefix: "Правило: ",
      syncCode: "синхронный код",
      allMicrotasks: "все микрозадачи",
      microtaskExamples: " (Promise.then, queueMicrotask, код после await) ",
      macrotasks: "макрозадачи",
      macrotaskExamples: " (setTimeout) по одной, и после каждой — снова все микрозадачи.",
    },
  },
  answerConsole: {
    title: "Console — твой прогноз",
    remove: "убрать",
    expected: "→ должно быть ",
  },
  tokenPicker: {
    instruction: "НАЖИМАЙ В ТОМ ПОРЯДКЕ, В КОТОРОМ ПОЯВИТСЯ ВЫВОД",
  },
  eventLoopViz: {
    callbackRunning: "Выполняем колбэк из очереди",
    drainMicrotasks: "Стек пуст — очищаем microtask queue",
    takeMacrotask: "Стек пуст — берём одну macrotask",
    waiting: "Ожидаем работу очередей",
    previousStep: "Предыдущий шаг",
    restart: "Запустить заново",
    pause: "Пауза",
    continue: "Продолжить",
    nextStep: "Следующий шаг",
    reason: "Почему этот шаг?",
    callStack: "Call Stack",
    empty: "пусто",
    flowAriaLabel: "Состояние цикла событий",
    microtaskQueue: "Microtask Queue · FIFO →",
    taskQueue: "Task Queue · FIFO →",
    nextQueueItem: (item: string) => `следующая: ${item}`,
    console: "CONSOLE",
    noOutput: "вывода пока нет",
    pending: "ожидают",
  },
} as const;
